version: '3'

services:
  redis:
    image: redis:4.0.9-alpine
    ports:
      - "6379:6379"

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    depends_on:
      - kafka1
    ports:
      - "9000:80"

  driver-location:
    build:
      context: .
      dockerfile: driver-location/Dockerfile
    depends_on:
      - redis
    ports:
      - "7000:80"

  zombie-driver:
    build:
      context: .
      dockerfile: zombie-driver/Dockerfile

    ports:
     - "8000:80"

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    expose:
      - "2181"
    restart: always
    container_name: zookeeper

  kafka1:
    image: wurstmeister/kafka:2.12-2.3.0
    depends_on:
      - zookeeper
    ports:
      - "9093:9093"
    expose:
      - "9092"
    environment:
      KAFKA_CREATE_TOPICS: "locations:2:1"
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka1:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    restart: always
    container_name: kafkaeeper-server